# Training the model

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.metrics import explained_variance_score

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [3]:
data = pd.read_csv('..\Admission_Predict.csv')
data.columns = [c.replace(' ', '_') for c in data.columns]
data.columns = [c.replace('LOR_', 'LOR') for c in data.columns]
data.columns = [c.replace('Chance_of_Admit_', 'Chance_of_Admit') for c in data.columns]
data.columns = [c.replace('Chance_of_Admit', 'Admit') for c in data.columns]


In [4]:
from tensorflow import keras
X=data[['GRE_Score','TOEFL_Score','University_Rating','SOP','LOR','CGPA','Research']]
y = data["Admit"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=100)

In [49]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Activation
model = Sequential()
model.add(Dense(128, input_dim=7))
model.add(Activation('sigmoid'))
model.add(Dense(32))
model.add(Activation('sigmoid'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.compile(loss=tf.keras.losses.MeanSquaredLogarithmicError(),optimizer='adam', metrics=[tf.keras.metrics.RootMeanSquaredError()])
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_30 (Dense)             (None, 128)               1024      
_________________________________________________________________
activation_30 (Activation)   (None, 128)               0         
_________________________________________________________________
dense_31 (Dense)             (None, 32)                4128      
_________________________________________________________________
activation_31 (Activation)   (None, 32)                0         
_________________________________________________________________
dense_32 (Dense)             (None, 1)                 33        
_________________________________________________________________
activation_32 (Activation)   (None, 1)                 0         
Total params: 5,185
Trainable params: 5,185
Non-trainable params: 0
___________________________________________________

In [82]:
model.fit(X_train, y_train, epochs=2000, batch_size=100, verbose=0)
score = model.evaluate(X_test, y_test)
print(score)

4/4 [==============================] - 0s 0s/step - loss: 0.0018 - root_mean_squared_error: 0.0696
[0.0018018120899796486, 0.06956997513771057]


In [69]:
model.predict([[337, 118, 4, 4.5, 4.5, 9.65, 1]])

array([[0.9361446]], dtype=float32)

In [54]:
model.predict([[309,111,2,2.5,4,8.03,0]])

array([[0.64954674]], dtype=float32)

# Pickling

In [212]:
import os.path
if os.path.isfile('../tensorflow_neuralNetworks/tensorflow_neuralNetworks.h5') is False:
    model.save('../tensorflow_neuralNetworks/tensorflow_neuralNetworks.h5')

In [2]:
from tensorflow.keras.models import load_model
new_model=load_model('../tensorflow_neuralNetworks/tensorflow_neuralNetworks.h5')

In [3]:
new_model.predict([[337, 118, 4, 4.5, 4.5, 9.65, 1]])

array([[0.92634034]], dtype=float32)

In [5]:
new_model.predict([[337.0, 118.0, 4.0, 4.5, 4.5, 9.65, 1.0]])[0][0]

0.92634034